name: Linting CI

on:
  push:
    branches:
      - main
      - feature/integrate-ci
  pull_request:
    branches:
      - main

jobs:
  lint-logic:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g eslint stylelint stylelint-config-standard htmlhint globals @eslint/js

      - name: Run HTML Hint
        run: htmlhint "**/*.html"

      - name: Run Stylelint
        run: npx stylelint "**/*.css" --fix || npx stylelint "**/*.css"

      - name: Run ESLint
        run: eslint .